### ISSUE TITLE
Error running this on pro plan

### ISSUE THREAD

**Issue by Kevinvincentals** [grll/claude-code-grll-installer#2]
Hi! Is this hardcoded to use Opus? 

I was just trying to test this out with the pro plan (which Anthropic now allows to run claude code using Sonnet 4). 

Could it also support that?

`   },
    "content": [
      {
        "type": "text",
        "text": "API Error: 400 {\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"system: Invalid model name\"}}"
      }
    ]
  },
  "parent_tool_use_id": null,
  "session_id": "4c0a71b3-0b4e-43cd-9d70-a1671ea51ad8"
}
{
  "type": "result",
  "subtype": "success",
  "is_error": true,
  "duration_ms": 341,
  "duration_api_ms": 0,
  "num_turns": 1,
  "result": "API Error: 400 {\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"system: Invalid model name\"}}",
  "session_id": "4c0a71b3-0b4e-43cd-9d70-a1671ea51ad8",
  "total_cost_usd": 0,
  "usage": {
    "input_tokens": 0,
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "output_tokens": 0,
    "server_tool_use": {
      "web_search_requests": 0
    }
  }
}
Error: Process completed with exit code 1.`

**Comment by grll** [comment]
Hey yes sorry it's hardcoded with `is_max = True` for now in the credentials.json which then default to opus. You can set the model to "sonnet" by setting the model parameter in the `claude_code.yml` github workflow generated.

To be clear:

```yaml
      - name: Run Claude PR Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}
          timeout_minutes: "60"
          model: "YOUR_DESIRED_MODEL" 
```
